#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laptop_LINQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Laptop_Management")]
	public partial class LaptopDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLaptopInfo(LaptopInfo instance);
    partial void UpdateLaptopInfo(LaptopInfo instance);
    partial void DeleteLaptopInfo(LaptopInfo instance);
    #endregion
		
		public LaptopDBDataContext() : 
				base(global::Laptop_LINQ.Properties.Settings.Default.Laptop_ManagementConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LaptopDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LaptopDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LaptopDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LaptopDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LaptopInfo> LaptopInfos
		{
			get
			{
				return this.GetTable<LaptopInfo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LaptopInfo")]
	public partial class LaptopInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _LaptopID;
		
		private string _LaptopName;
		
		private string _LaptopType;
		
		private DateTime _ProductDate;
		
		private string _Processor;
		
		private System.Nullable<int> _HDD;
		
		private System.Nullable<int> _RAM;
		
		private System.Nullable<int> _Price;
		
		private string _ImageName;
	
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLaptopIDChanging(string value);
    partial void OnLaptopIDChanged();
    partial void OnLaptopNameChanging(string value);
    partial void OnLaptopNameChanged();
    partial void OnLaptopTypeChanging(string value);
    partial void OnLaptopTypeChanged();
    partial void OnProductDateChanging(System.Nullable<System.DateTime> value);
    partial void OnProductDateChanged();
    partial void OnProcessorChanging(string value);
    partial void OnProcessorChanged();
    partial void OnHDDChanging(System.Nullable<int> value);
    partial void OnHDDChanged();
    partial void OnRAMChanging(System.Nullable<int> value);
    partial void OnRAMChanged();
    partial void OnPriceChanging(System.Nullable<int> value);
    partial void OnPriceChanged();
    partial void OnImageNameChanging(string value);
    partial void OnImageNameChanged();
    #endregion
		
		public LaptopInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LaptopID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string LaptopID
		{
			get
			{
				return this._LaptopID;
			}
			set
			{
				if ((this._LaptopID != value))
				{
					this.OnLaptopIDChanging(value);
					this.SendPropertyChanging();
					this._LaptopID = value;
					this.SendPropertyChanged("LaptopID");
					this.OnLaptopIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LaptopName", DbType="VarChar(100)")]
		public string LaptopName
		{
			get
			{
				return this._LaptopName;
			}
			set
			{
				if ((this._LaptopName != value))
				{
					this.OnLaptopNameChanging(value);
					this.SendPropertyChanging();
					this._LaptopName = value;
					this.SendPropertyChanged("LaptopName");
					this.OnLaptopNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LaptopType", DbType="VarChar(50)")]
		public string LaptopType
		{
			get
			{
				return this._LaptopType;
			}
			set
			{
				if ((this._LaptopType != value))
				{
					this.OnLaptopTypeChanging(value);
					this.SendPropertyChanging();
					this._LaptopType = value;
					this.SendPropertyChanged("LaptopType");
					this.OnLaptopTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductDate", DbType="Date")]
		public DateTime ProductDate
		{
			get
			{
				return this._ProductDate;
			}
			set
			{
				if ((this._ProductDate != value))
				{
					this.OnProductDateChanging(value);
					this.SendPropertyChanging();
					this._ProductDate = value;
					this.SendPropertyChanged("ProductDate");
					this.OnProductDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Processor", DbType="VarChar(100)")]
		public string Processor
		{
			get
			{
				return this._Processor;
			}
			set
			{
				if ((this._Processor != value))
				{
					this.OnProcessorChanging(value);
					this.SendPropertyChanging();
					this._Processor = value;
					this.SendPropertyChanged("Processor");
					this.OnProcessorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HDD", DbType="Int")]
		public System.Nullable<int> HDD
		{
			get
			{
				return this._HDD;
			}
			set
			{
				if ((this._HDD != value))
				{
					this.OnHDDChanging(value);
					this.SendPropertyChanging();
					this._HDD = value;
					this.SendPropertyChanged("HDD");
					this.OnHDDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RAM", DbType="Int")]
		public System.Nullable<int> RAM
		{
			get
			{
				return this._RAM;
			}
			set
			{
				if ((this._RAM != value))
				{
					this.OnRAMChanging(value);
					this.SendPropertyChanging();
					this._RAM = value;
					this.SendPropertyChanged("RAM");
					this.OnRAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Int")]
		public System.Nullable<int> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageName", DbType="VarChar(100)")]
		public string ImageName
		{
			get
			{
				return this._ImageName;
			}
			set
			{
				if ((this._ImageName != value))
				{
					this.OnImageNameChanging(value);
					this.SendPropertyChanging();
					this._ImageName = value;
					this.SendPropertyChanged("ImageName");
					this.OnImageNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
